Add TimestampStyle enum
brazier-dev/hikari-toolbox pull request #26
Opened 2023-04-29 19:33 UTC by owenwastaken

- Add a `TimestampStyle` enum containing all the types of Discord timestamps
- Refactor `format_dt` to take a `TimestampStyle` value instead of a string
- Modify `test_has_style` test to use a `TimestampStyle` enum instead of a string
- Remove unnecessary `test_invalid_style` test

Note: This is a breaking change

Let me know if there is any changes you would like me to make.

2023-04-29 19:34 UTC, HyperGH approved these changes

2023-04-29 19:36 UTC, Lunarmagpie approved these changes
i like this change

2023-04-29 19:36 UTC, Lunarmagpie commented
just make sure tests pass

2023-04-29 19:37 UTC, HyperGH requested changes
They do not.

2023-04-29 22:30 UTC, owenwastaken commented
It seems that the tests that failed were not caused by the code in this PR.

2023-04-30 02:36 UTC, Lunarmagpie commented
I will fix the tests for this

2023-04-30 12:11 UTC, HyperGH approved these changes

2023-04-30 12:12 UTC, merged

2023-04-30 12:12 UTC, HyperGH commented
Thanks for the PR!